routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('halamanutama.index');
});
Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('/daftarkost', 'App\Http\Controllers\KostController@indexkost')->name('kost');
Route::get('/fas', 'App\Http\Controllers\FasilitasController@indexfas');

// Route untuk cek role
Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'cek_login:1'], function () {
        Route::resource('penyewa', 'App\Http\Controllers\PenyewaController');
        Route::post('/penyewa/konfirmasi/{id}', 'App\Http\Controllers\PenyewaController@konfirmasi')->name('penyewa.konfirmasi');
        //manajemen data pengunjung
        Route::get('/indexpengunjung', 'App\Http\Controllers\PenyewaController@indexpengunjung');
        Route::resource('fasilitas','App\Http\Controllers\FasilitasController');
    });
    Route::group(['middleware' => 'cek_login:4'], function () {
        Route::get('/pengunjung', 'App\Http\Controllers\PenyewaController@pengunjung');
        Route::post('/pengunjung/store/','App\Http\Controllers\PenyewaController@store');
    });
    Route::group(['middleware' => 'cek_login:5'], function () {
        Route::resource('user','App\Http\Controllers\UserController');
    });
    Route::group(['middleware' => 'cek_login:6'], function () {
        Route::get('/booking/pesan/{id}','App\Http\Controllers\BookingController@create');
        Route::post('/booking/store/{id}', 'App\Http\Controllers\BookingController@store');
    });
    Route::resource('booking','App\Http\Controllers\BookingController');
    Route::resource('dashboard', 'App\Http\Controllers\DashboardController');
    Route::resource('pembayaran', 'App\Http\Controllers\PembayaranController');
    Route::get('/pembayaran/create/{id}', 'App\Http\Controllers\PembayaranController@create')->name('pembayaran.create');
    Route::post('/pembayaran/konfirmasi/{id}', 'App\Http\Controllers\PembayaranController@konfirmasi');
    Route::post('/pembayaran/konfirmasi/admin/{id}', 'App\Http\Controllers\PembayaranController@konfirmasiadmin')->name('admin.konfirmasi');
    Route::resource('komplain','App\Http\Controllers\KomplainController');
    Route::post('/komplain/konfirmasi/{id}', 'App\Http\Controllers\KomplainController@konfirmasi')->name('komplain.konfirmasi');
    Route::resource('kost','App\Http\Controllers\KostController');
    Route::get('/notabooking/{id}','App\Http\Controllers\BookingController@NotaBooking');
    Route::get('/notapembayaran/{id}','App\Http\Controllers\PembayaranController@NotaPembayaran');
    Route::get('/profil/{id}','App\Http\Controllers\BerandaController@profil');
    Route::get('/ganti-password/{id}','App\Http\Controllers\BerandaController@password');
    Route::put('/ganti-password/{id}','App\Http\Controllers\BerandaController@gantipassword')->name('profil.update');
});
// require __DIR__ . '/auth.php';

// php artisan db:seed

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Pembayaran.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pembayaran extends Model
{
    use HasFactory;
    protected $table = 'pembayaran';
    protected $fillable = ['user_id','kost_id','fas_id','nama_penyewa','tgl_booking','tgl_masuk','tgl_bayar','bukti','status_bayar','bulan'];



    public function booking()
    {
        return $this->hasOne('App\Models\Booking', 'id', 'booking_id');
    }
    public function kost()
    {
        return $this->belongsTo(Kost::class);
    }
}

app/Http/Controllers/PembayaranController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pembayaran;
use App\Models\User;
use App\Models\Kost;
use App\Models\Fasilitas;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use PDF;
class PembayaranController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == '6') {
            $pembayaran = Pembayaran::where('user_id', Auth::user()->id)
            ->Where('status_bayar', '!=', 'Diterima(Booking)')->get()->unique('tgl_bayar');
            $ids = Pembayaran::where('user_id', Auth::user()->id)->latest('tenggat')->first();
            return view('pembayaran.index', compact('pembayaran', 'ids'));
        } elseif (Auth::user()->role_id == '1') {
            $pembayaran = Pembayaran::where('status_bayar', 'Diterima')
            ->orWhere('status_bayar', 'Sudah Transfer')
            ->orwhere('status_bayar', 'Ditolak')
            ->orwhere('status_bayar', 'Menunggu Konfirmasi')->get()->unique('tgl_bayar');
            return view('pembayarans.index', ['pembayaran' => $pembayaran]);
        }
    }

    public function NotaPembayaran($id)
    {
        $no = random_int(100000, 999999);
        $nama = Auth::user()->name;
        $cek = Pembayaran::find($id);
            if (empty($cek->fas_id)) {
                $pembayaran = Pembayaran::join('kost','kost.id','=','pembayaran.kost_id')
                ->where('pembayaran.id',$cek->id)
                ->select('pembayaran.*', 'kost.nama_kost')->first();
            } else {
                $pembayaran = Pembayaran::join('kost','kost.id','=','pembayaran.kost_id')
                ->join('fasilitas','fasilitas.id','=','pembayaran.fas_id')
                ->where('pembayaran.id',$cek->id)
                ->select('pembayaran.*', 'kost.nama_kost','fasilitas.fasilitas','fasilitas.harga')->first();
            }
        $customPaper = array(0, 0,155.90551181,206.92913386);
        $pdf = PDF::loadview('pembayaran.cetak',['no' => $no, 'nama' => $nama,'pembayaran' => $pembayaran])->setPaper($customPaper,'portrait');
        return $pdf->download('Nota Pembayaran '.$nama.' Bulan '.$pembayaran->bulan.'.pdf');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $cek = Pembayaran::findorfail($id);
        if (empty($cek->fas_id)) {
            $Idfasilitas = [];
            $pembayaran =  DB::table('pembayaran')
            ->join('kost','kost.id','=','pembayaran.kost_id')
            ->where('pembayaran.id', $cek->id)
            ->select('pembayaran.*','kost.nama_kost')->first();
            $fasilitas = Fasilitas::all();
            $user = User::all();
            $kost = Kost::all();
            return view('pembayaran.create', compact('user','pembayaran','kost','fasilitas','Idfasilitas'));
        } else {
            $Idfasilitas = [];
            $pembayaran =  DB::table('pembayaran')
            ->join('fasilitas','fasilitas.id','=','pembayaran.fas_id')
            ->join('kost','kost.id','=','pembayaran.kost_id')
            ->where('pembayaran.id', $cek->id)
            ->select('pembayaran.*','fasilitas.harga','fasilitas.fasilitas','kost.nama_kost')->first();
            $fasilitas = Fasilitas::all();
            $user = User::all();
            $kost = Kost::all();
            foreach (listsFasilitas($pembayaran->tgl_bayar) as $key) {
                $Idfasilitas[] = $key->fas_id;
            }
            return view('pembayaran.create', compact('user','pembayaran','kost','fasilitas','Idfasilitas'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $input = $request->all();
        if (empty($input['fas_id'])) {
            $pembayaran = new Pembayaran;
            $pembayaran->user_id = $request->user_id;
            $pembayaran->kost_id = $request->kost_id;
            $pembayaran->nama_penyewa = $request->nama_penyewa;
            $pembayaran->tgl_masuk = $request->tgl_masuk;
            $pembayaran->tgl_booking = $request->tgl_booking;
            $pembayaran->status_bayar = "Menunggu Konfirmasi";
            $pembayaran->tgl_bayar = Carbon::now()->toDateString();
            $pembayaran->save();
            $pembayaran->id;
        } else {
            for($i = 0; $i < count($input['fas_id']); $i++){
                $ids[] = Pembayaran::insertGetId($request->except(['fas_id','_token','tenggat','bukti','tgl_bayar'])+[
                    'fas_id' => $input['fas_id'][$i],
                    'status_bayar' => 'Menunggu Konfirmasi',
                    'tgl_bayar' => Carbon::now()->toDateString(),
                    'created_at' => Carbon::now()->toDateTimeString()
                ]);
            }
            $pembayaran = Pembayaran::whereIn('id', $ids)->first();
        }
        return redirect()->route('pembayaran.show', $pembayaran  )->with('toast_success', 'Segera Lakukan Pembayaran!!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pembayaran  $pembayaran
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Auth::user()->role_id == '6') {
            $cek = Pembayaran::find($id);
            if (empty($cek->fas_id)) {
                $pembayaran = Pembayaran::join('kost','kost.id','=','pembayaran.kost_id')
                ->where('pembayaran.id',$cek->id)
                ->select('pembayaran.*', 'kost.nama_kost')->first();
            } else {
                $pembayaran = Pembayaran::join('kost','kost.id','=','pembayaran.kost_id')
                ->join('fasilitas','fasilitas.id','=','pembayaran.fas_id')
                ->where('pembayaran.id',$cek->id)
                ->select('pembayaran.*', 'kost.nama_kost','fasilitas.fasilitas','fasilitas.harga')->first();
            }
            return view('pembayaran.show', compact('pembayaran','cek'));
        } elseif (Auth::user()->role_id == '1') {
            $cek = Pembayaran::find($id);
            if (empty($cek->fas_id)) {
                $pembayaran = Pembayaran::join('kost','kost.id','=','pembayaran.kost_id')
                ->where('pembayaran.id',$cek->id)
                ->select('pembayaran.*', 'kost.nama_kost')->first();
            } else {
                $pembayaran = Pembayaran::join('kost','kost.id','=','pembayaran.kost_id')
                ->join('fasilitas','fasilitas.id','=','pembayaran.fas_id')
                ->where('pembayaran.id',$cek->id)
                ->select('pembayaran.*', 'kost.nama_kost','fasilitas.fasilitas','fasilitas.harga')->first();
            }
            return view('pembayaran.show', compact('pembayaran','cek'));
        }
    }

    public function showbulan($bln)
    {
        $pembayaran = Pembayaran::where('bulan',$bln)->paginate();
        return view('pembayarans.bulan',compact('pembayaran'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pembayaran  $pembayaran
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pembayaran = Pembayaran::join('fasilitas','fasilitas.id', '=', 'pembayaran.fas_id')
        ->where('pembayaran.id',$id)
        ->select('pembayaran.*', 'fasilitas.fasilitas', 'fasilitas.harga')->first();
        $user = User::all();
        $fasilitas = Fasilitas::all();
        return view('pembayaran.edit', ['pembayaran' => $pembayaran, 'user' => $user,'fasilitas' => $fasilitas]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Pembayaran  $pembayaran
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        Pembayaran::where('id', $id)
            ->update([
                'nama_penyewa' => $request->nama_penyewa,
                'tgl_bayar' => $request->tgl_bayar,
                'bulan' => $request->bulan,
                'fas_id' => $request->fasilitas

            ]);

        return redirect('/pembayaran')->with('toast_info', 'Data berhasil diubah!');
    }

    public function konfirmasi(Request $request, $id)
    {
        $images = $request->file('bukti');
        $imagebukti = 'bukti' . time() . '.' . $images->extension();
        $images->move(public_path('images'), $imagebukti);

        Pembayaran::where('id', $id)
            ->update([
                'bukti' => $imagebukti,
                'status_bayar' => $request->status

            ]);
        return redirect('/pembayaran')->with('toast_info', 'Berhasil Melakukan Pembayaran!!');
    }

    public function konfirmasiadmin(Request $request, $id)
    {
        if ($request->status == 'Ditolak') {
            Pembayaran::where('id', $id)
            ->update([
                'status_bayar' => $request->status
            ]);
            return redirect('/pembayaran')->with('toast_danger', 'Pembayaran Ditolak!');
        } elseif ($request->status == 'Diterima(Booking)') {
            Pembayaran::where('id', $id)
            ->update([
                'status_bayar' => $request->status
            ]);
            return redirect('/booking')->with('toast_success', 'Booking Diterima!');
        } elseif ($request->status == 'Ditolak(Booking)') {
            Pembayaran::where('id', $id)
            ->update([
                'status_bayar' => $request->status
            ]);
            return redirect('/booking')->with('toast_danger', 'Booking Ditolak!');
        } else {
            $tgl_bayar = Carbon::now();
            Pembayaran::where('id', $id)
            ->update([

resources/views/pembayaran/cetak.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nota Pembayaran</title>
    <style>
        .garis{
            border: 1px solid;
            font-size: 12px;
        }
        @page { margin: 1px; }
    </style>

</head>
<body>
    <div class="garis">
    <table>
        <tr>
            <td>
                <center>
                    <font size="3">Kost Bu Tik</font><br>
                    <font size="1"><i>Jl. Margo Tani 01 Sukorame, Kec. Mojoroto</i></font><br>
                    <font size="1"><i>Kota Kediri</i></font><br>
                    <font size="1">BCA 033278142 a.n. Suyatik</font>
                </center>
            </td>
        </tr>
    </table>
    <hr>
    <center><b>NOTA PEMBAYARAN</b></center><br>
    <table>
        @php
        $harga_kost = $pembayaran->kost->harga;
        $total_fasilitas = $total_biaya = 0;
        @endphp
        @foreach(listsFasilitas($pembayaran->tgl_bayar ) as $row)
        @php
            $total_fasilitas += $row->harga;
            $total_biaya = $harga_kost + $total_fasilitas;
        @endphp
        @endforeach
        <tr>
            <td>
                No. Pembayaran
            </td>
            <td>: {{$no}}</td>
        </tr>
        <tr>
            <td>
                Nama
            </td>
            <td>: {{$nama}}</td>
        </tr>
        <tr>
            <td>
                Kamar
            </td>
            <td>: {{$pembayaran->nama_kost}}</td>
        </tr>
        <tr>
            <td>
                Bulan
            </td>
            <td>: {{$pembayaran->bulan}}</td>
        </tr>
        <tr>
            <td>
                Fasilitas
            </td>
            @if(empty($pembayaran->fas_id))
            <td>: -</td>
            @else
            <td>: @foreach(listsFasilitas($pembayaran->tgl_bayar ) as $row)
                {{ $loop->first ? '' : ', ' }}
                {{$row->fasilitas}}
                @endforeach
            </td>
            @endif
        </tr>
        <tr>
            <td>
                Total
            </td>
            @if(empty($pembayaran->fas_id))
            <td>: Rp. {{ $harga_kost}}</td>
            @else
            <td>: Rp. {{ $total_biaya}}</td>
            @endif
        </tr>
    </table>
    </div>
</body>
</html>

resources/views/pembayaran/create.blade.php
<!-- menampilkan berdasarkan file index di folder layouts  -->
@extends('layouts.index')
<!-- section untu title  -->
@section('title', 'Data Pembayaran')
<!-- section untuk content  -->
@section('content')

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Input Pembayaran</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <div class="row">

                            <div class="col-md-12 col-lg-8 entries">
                                @csrf
                                <article class="entry">
                                    <form action="{{ route('pembayaran.store')}}" method="post" enctype="multipart/form-data">
                                        @csrf
                                        <div class="card-body">
                                            <div class="position-relative form-group mt-4 entry-content">
                                                <label for="nama_penyewa" class="">
                                                    <p style="font-weight: bold;">Nama Pelanggan</p>
                                                </label>
                                                <input name="nama_penyewa" id="nama_penyewa" type="text" class="form-control" value="{{Auth::user()->name}}" readonly>
                                                <input name="user_id" id="user_id" type="hidden" class="form-control" value="{{Auth::user()->id}}">
                                                <input name="tgl_booking" id="tgl_booking" value="{{$pembayaran->tgl_booking}}" type="hidden" class="form-control" readonly>
                                                <input name="tgl_masuk" id="tgl_masuk" value="{{$pembayaran->tgl_masuk}}" type="hidden" class="form-control" readonly>
                                            </div>
                                            <div class="position-relative form-group mt-4 entry-content">
                                                <label for="nama_kost" class="">
                                                    <p style="font-weight: bold;">Nama Kamar</p>
                                                </label>
                                                <input name="" id="nama_kost" type="text" class="form-control" value="{{$pembayaran->nama_kost}}" readonly>
                                                <input name="kost_id" id="kost_id" value="{{$pembayaran->kost_id}}" type="hidden">
                                            </div>
                                            <div class="form-group">
                                                <label for="fas" style="font-weight: bold;">Fasilitas Tambahan</label>
                                                <select class="js-example-theme-multiple js-states form-control" id="fas_id" name="fas_id[]" multiple="multiple">

                                                    @if ($pembayaran->fas_id == "")
                                                    @foreach ($fasilitas as $item)
                                                    <option value="{{$item->id }}"> {{$item->fasilitas}} - {{$item->harga}}</option>
                                                    @endforeach
                                                    @else
                                                    @foreach ($fasilitas as $item)
                                                    @if(in_array($item->id, $Idfasilitas))
                                                    <option value="{{$item->id }}" selected> {{$item->fasilitas}}</option>
                                                    @else
                                                    <option value="{{$item->id }}"> {{$item->fasilitas}} - {{$item->harga}}</option>
                                                    @endif
                                                    @endforeach
                                                    @endif
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-primary mt-4"><i class="pe-7s-diskette"></i> Simpan Data</button>
                                    </form>
                                </article>
                            </div><!-- End blog entries list -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End Blog Section -->
</main>
<!-- End #main -->
@endsection
@section('script')
<script>
    function previewbukti(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function() {
                $('#previewbukti').attr("src", reader.result);
            }
            reader.readAsDataURL(file);
        }
    }
</script>
@endsection

resources/views/pembayaran/edit.blade.php
<!-- menampilkan berdasarkan file index di folder layouts  -->
@extends('layouts.index')
<!-- section untu title  -->
@section('title', 'Data Pembayaran')
<!-- section untuk content  -->
@section('content')

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Data Pembayaran</h3>
                        </div>

                        <div class="card-body">
                            <form action="{{route('pembayaran.update', $pembayaran->id)}}" method="post" enctype="multipart/form-data">
                                <!--  untuk keamanan -->
                                @method('PUT') 
                                @csrf
                                <div class="form-group">
                                    <label for="nama_penyewa" style="font-weight: bold;">Nama Penyewa</label>
                                    <input type="text" class="form-control" id="al" name="nama_penyewa" value="{{$pembayaran['nama_penyewa']}}" placeholder="Masukkan nama_penyewa" readonly>
                                </div>
                                <div class="form-group">
                                    <label for="tgl_bayar" style="font-weight: bold;">Tanggal Pembayaran</label>
                                    <input type="date" class="form-control" id="al" name="tgl_bayar" value="{{$pembayaran['tgl_bayar']}}" placeholder="Masukkan tgl_masuk" required>
                                </div>
                                <div class="form-group">
                                    <label for="bulan" style="font-weight: bold;">Bulan</label>
                                    <select class="form-control" name="bulan">
                                            <option value="{{$pembayaran->bulan}}">@if(empty($pembayaran->bulan)) Pilih Bulan @else {{$pembayaran->bulan}} @endif </option>
                                                <option value="snuari">Januari</option>
                                                <option value="Februari">Februari</option>
                                                <option value="Maret">Maret</option>
                                                <option value="April">April</option>
                                                <option value="Mei">Mei</option>
                                                <option value="Juni">Juni</option>
                                                <option value="Juli">Juli</option>
                                                <option value="Agustus">Agustus</option>
                                                <option value="September">September</option>
                                                <option value="Oktober">Oktober</option>
                                                <option value="November">November</option>
                                                <option value="Desember">Desember</option>
                                        </select>
                                </div>
                                <div class="form-group">
                                    <label for="fas" style="font-weight: bold;">Fasilitas Tambahan</label>
                                    <select class="form-control" name="fasilitas">
                                        @if(empty($pembayaran['fas_id']))
                                        <option value="">Pilih Fasilitas</option>
                                        @else
                                        <option value="{{$pembayaran['fas_id']}}">{{$pembayaran->fasilitas}}</option>
                                        @endif
                                        @foreach ($fasilitas as $item)
                                            <option value="{{ $item->id }}">{{ $item->fasilitas}} - {{ $item->harga}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary"><i class="pe-7s-diskette"></i> Update Data</button>

                                <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>

                    <!-- /.card -->
    </section><!-- End Breadcrumbs -->

    @endsection