routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('halamanutama.index');
});
Route::get('/welcome', function () {
    return view('welcome');
});

Route::get('/daftarkost', 'App\Http\Controllers\KostController@indexkost')->name('kost');
Route::get('/fas', 'App\Http\Controllers\FasilitasController@indexfas');

// Route untuk cek role
Route::group(['middleware' => 'auth'], function () {
    Route::group(['middleware' => 'cek_login:1'], function () {
        Route::resource('penyewa', 'App\Http\Controllers\PenyewaController');
        Route::post('/penyewa/konfirmasi/{id}', 'App\Http\Controllers\PenyewaController@konfirmasi')->name('penyewa.konfirmasi');
        //manajemen data pengunjung
        Route::get('/indexpengunjung', 'App\Http\Controllers\PenyewaController@indexpengunjung');
        Route::resource('fasilitas','App\Http\Controllers\FasilitasController');
    });
    Route::group(['middleware' => 'cek_login:4'], function () {
        Route::get('/pengunjung', 'App\Http\Controllers\PenyewaController@pengunjung');
        Route::post('/pengunjung/store/','App\Http\Controllers\PenyewaController@store');
    });
    Route::group(['middleware' => 'cek_login:5'], function () {
        Route::resource('user','App\Http\Controllers\UserController');
    });
    Route::group(['middleware' => 'cek_login:6'], function () {
        Route::get('/booking/pesan/{id}','App\Http\Controllers\BookingController@create');
        Route::post('/booking/store/{id}', 'App\Http\Controllers\BookingController@store');
    });
    Route::resource('booking','App\Http\Controllers\BookingController');
    Route::resource('dashboard', 'App\Http\Controllers\DashboardController');
    Route::resource('pembayaran', 'App\Http\Controllers\PembayaranController');
    Route::get('/pembayaran/create/{id}', 'App\Http\Controllers\PembayaranController@create')->name('pembayaran.create');
    Route::post('/pembayaran/konfirmasi/{id}', 'App\Http\Controllers\PembayaranController@konfirmasi');
    Route::post('/pembayaran/konfirmasi/admin/{id}', 'App\Http\Controllers\PembayaranController@konfirmasiadmin')->name('admin.konfirmasi');
    Route::resource('komplain','App\Http\Controllers\KomplainController');
    Route::post('/komplain/konfirmasi/{id}', 'App\Http\Controllers\KomplainController@konfirmasi')->name('komplain.konfirmasi');
    Route::resource('kost','App\Http\Controllers\KostController');
    Route::get('/notabooking/{id}','App\Http\Controllers\BookingController@NotaBooking');
    Route::get('/notapembayaran/{id}','App\Http\Controllers\PembayaranController@NotaPembayaran');
    Route::get('/profil/{id}','App\Http\Controllers\BerandaController@profil');
    Route::get('/ganti-password/{id}','App\Http\Controllers\BerandaController@password');
    Route::put('/ganti-password/{id}','App\Http\Controllers\BerandaController@gantipassword')->name('profil.update');
});
// require __DIR__ . '/auth.php';

// php artisan db:seed

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Models\Penyewa;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function penyewa()
    {
        return $this->hasOne(Penyewa::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class UserController extends Controller
{
    public function index()
    {
        $user = User::all();

        return view('user.index', ['user'=> $user]);
    }
    public function destroy($id)
    {
        $data = User::findOrFail($id);
        $data->delete();
        return redirect('user')->with('success','Berhasil Menghapus Data User');
    }
    public function create()
    {
        return view('user.create');
    }
    public function store(Request $request)
    {
        $user = User::create([
            'name' => $request->nama,
            'email' => $request->email,
            'password' => bcrypt('12345678'),
            'role_id' => '1'
        ]);
        $user->remember_token = Str::random(60);
        $user->save();
        return redirect('/user')->with('success','Berhasil Menambah Data User');
    }
    public function search(Request $request){

        $cari = $request->cari;

        $user = User::where('name', 'like', "%".$cari."%")->paginate(5);

        session()->flashInput($request->input());

        return view('user.index', ['user' => $user]);
    }
}

resources/views/user/create.blade.php
<!-- menampilkan berdasarkan file index di folder layouts  -->
@extends('layouts.index')
<!-- section untu title  -->
@section('title', 'Tambah Data User')
<!-- section untuk content  -->
@section('content')

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Input Data User</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="row">
                            <div class="col-md-12 col-lg-8 entries">
                                @csrf
                                <article class="entry">
                                    <form action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
                                        @csrf
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="position-relative form-group">
                                                    <label for="name" style="font-weight: bold;">Nama</label>
                                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="nama" name="nama" placeholder="Masukan Nama" required>
                                                    @error('name')
                                                <span class="invalid-feedback" role="alert">
                                                    {{ $message }}
                                                </span>
                                                @enderror
                                            </div>
                                                <div class="position-relative form-group">
                                                    <label for="name" style="font-weight: bold;">Email</label>
                                                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="email" name="email" placeholder="Masukan Email" required>
                                                    @error('name')
                                                <span class="invalid-feedback" role="alert">
                                                    {{ $message }}
                                                </span>
                                                @enderror
                                            </div>
                                                <div class="position-relative form-group">
                                                    <label for="name" style="font-weight: bold;">Role</label>
                                                    <input type="text" value="Admin" class="form-control" id="role_id" name="role_id" readonly>
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary"><i class="pe-7s-diskette"></i> Simpan Data</button>
                                    </form>
                                </article>
                            </div><!-- End blog entries list -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End Blog Section -->

</main>
<!-- End #main -->
@endsection

resources/views/user/edit.blade.php
<!-- menampilkan berdasarkan file index di folder layouts  -->
@extends('layouts.index')
<!-- section untu title  -->
@section('title', 'Tambah Data User')
<!-- section untuk content  -->
@section('content')

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Input Data User</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="row">
                            <div class="col-md-12 col-lg-8 entries">
                                @csrf
                                <article class="entry">
                                    <form action="{{route('user.store')}}" method="post" enctype="multipart/form-data">
                                        @csrf
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="position-relative form-group">
                                                    <label for="name" style="font-weight: bold;">Nama</label>
                                                    <input type="text" class="form-control" id="nama" name="nama" placeholder="Masukan Nama" required>
                                                </div>
                                                <div class="position-relative form-group">
                                                    <label for="name" style="font-weight: bold;">Email</label>
                                                    <input type="text" class="form-control" id="email" name="email" placeholder="Masukan Email" required>
                                                </div>
                                                <div class="position-relative form-group">
                                                    <label for="name" style="font-weight: bold;">Role</label>
                                                    <select class="form-control" name="role">
                                                    <option value="" selected>Pilih Role</option>
                                                    @foreach($roles as $data)
                                                    <option value="{{ $data->name }}">{{ $data->display_name }}</option>
                                                    @endforeach
                                                </select>
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary"><i class="pe-7s-diskette"></i> Simpan Data</button>
                                    </form>
                                </article>
                            </div><!-- End blog entries list -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End Blog Section -->

</main>
<!-- End #main -->
@endsection
@section('script')
<script>
    function previewbukti(input) {
        var file = $("input[type=file]").get(0).files[0];
        if (file) {
            var reader = new FileReader();
            reader.onload = function() {
                $('#previewbukti').attr("src", reader.result);
            }
            reader.readAsDataURL(file);
        }
    }
</script>
@endsection

resources/views/user/index.blade.php
<!-- menampilkan berdasarkan file index di folder layouts  -->
@extends('layouts.index')
<!-- section untu title  -->
@section('title', 'Data User')
<!-- section untuk content  -->
@section('content')
<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Data User</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <div class="col-md-12">
                            <div class="card-body">
                                <div class="tab-content">
                                    <div class="table-responsive">
                                        <a href="{{ route('user.create') }}" class="btn btn-success btn-pill mb-3">Tambah Admin</a>
                                        <table id="example" class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th scope='col'>No</th>
                                                    <th scope='col'>Username</th>
                                                    <th scope='col'>Email</th>
                                                    <th scope='col'>Level</th>
                                                    <th scope='col'>Tanggal Buat</th>
                                                    <th scope="col">Aksi</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            @php $no = 0; @endphp
                                            @foreach($user as $usr)
                                            @php $no++; @endphp
                                                <tr>
                                                    <th scope='row'>{{$no}}</th>
                                                    <td>{{$usr->name}}</td>
                                                    <td>{{$usr->email}}</td>
                                                    <td>
                                                        @if($usr->role_id == 1)
                                                            Admin
                                                            @elseif ($usr->role_id == 4)
                                                            Pengunjung
                                                            @elseif($usr->role_id == 5)
                                                            Pemilik
                                                            @elseif($usr->role_id == 6)
                                                            Penyewa
                                                        @endif
                                                    </td>
                                                    <td>{{$usr->created_at}}</td>
                                                    <td>
                                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="{{ route('user.destroy', $usr->id) }}" method="POST">
                                                            @csrf
                                                            @method('DELETE')
                                                            @if ($usr->role_id == 5)
                                                            <button type="submit" class="fas fa-trash-alt bg-danger p-2 text-white rounded delete" title="hapus" disabled></button>
                                                            @else
                                                            <button type="submit" class="fas fa-trash-alt bg-danger p-2 text-white rounded delete" title="hapus"></button>
                                                            @endif
                                                        </form>
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
@endsection